FROM python:3.8

ENV PYTHONUNBUFFERED 1

WORKDIR /usr/noteProject

COPY ./requirements.txt /usr/noteProject

RUN ["pip", "install", "-r", "requirements.txt"]

COPY ./ /usr/noteProject/

ENTRYPOINT [ "python", "manage.py", "runserver", "0.0.0.0:8000"]
